# ai_orch.py
from ohlc_predictor import OHLC_Predictor
#from sim_ohlc_predictor import SimOHLC_Predictor as OHLC_Predictor
from trade_enricher import enrich_signals
from ai_signal_updater import update_ai_signals
from db_utils import get_db_connection
import yaml
import pandas as pd


def run_ai_cycle() -> str:
    """
    Run a single AI prediction -> enrichment -> DB update cycle safely.
    Returns:
        str: 'done' when finished.
    """

    # -------------------------------
    # Load configuration
    # -------------------------------
    with open("config.yaml", "r") as f:
        config = yaml.safe_load(f)

    # -------------------------------
    # Initialize predictor
    # -------------------------------
    predictor = OHLC_Predictor(
        db_path=config["DB_PATH"],   # ✅ SINGLE SOURCE OF TRUTH
        clf_model=config["classifier_model"],
        reg_model=config["regressor_model"],
        features=config["features"],
        prob_threshold=config["prob_threshold"]
    )

    # -------------------------------
    # Run raw AI predictions
    # -------------------------------
    signals_df = predictor.run_predictions()

    if signals_df.empty:
        print("⚠️ No signals generated: prediction output is empty.")
        return "done"

    if "decision" not in signals_df.columns:
        print(
            f"⚠️ 'decision' column missing. Columns: {signals_df.columns.tolist()}"
        )
        return "done"

    # Keep only BUY signals
    buy_signals_df = signals_df[signals_df["decision"] == "BUY"]

    if buy_signals_df.empty:
        print("⚠️ No BUY signals generated by AI this cycle.")
        return "done"

    # -------------------------------
    # Fetch latest prices for enrichment
    # -------------------------------
    try:
        conn = get_db_connection()
        prices_df = pd.read_sql(
            """
            SELECT t1.pair_id, t1.close AS price
            FROM ohlc_data t1
            INNER JOIN (
                SELECT pair_id, MAX(time) AS max_time
                FROM ohlc_data
                GROUP BY pair_id
            ) t2
            ON t1.pair_id = t2.pair_id
            AND t1.time = t2.max_time
            """,
            conn
        )
        conn.close()
    except Exception as e:
        print(f"❌ Failed to fetch prices from DB: {e}")
        return "done"

    # -------------------------------
    # Enrich BUY signals
    # -------------------------------
    trade_ready_df = enrich_signals(
        buy_signals_df,
        current_prices=prices_df
    )

    if trade_ready_df.empty:
        print("⚠️ No trade-ready signals after enrichment.")
        return "done"

    # -------------------------------
    # Update AI signals DB
    # -------------------------------
    try:
        update_ai_signals(trade_ready_df)
        print("✅ AI signals DB updated successfully.")
    except Exception as e:
        print(f"❌ Failed to update AI signals DB: {e}")

    return "done"


if __name__ == "__main__":
    run_ai_cycle()
